"""Quality report for a run: docs/datasets-quality/<run_id>.md (Task 2d item 3).

Per dataset: row counts, rows missing a source record (must be zero), gap rows (no source
record, with a stated reason), duplicate checks, match-grade distribution, and null counts
with their reasons. The report contains counts only, never vendor data: reasons are
scrubbed of IDs, URLs and names before they are counted.
"""
import hashlib
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

from apps.api.core.provenance import ROOT

REPORT_DIR = ROOT / "docs" / "datasets-quality"
RUN_FIELDS = {"dataset", "run_id", "source_record_id"}
GRADE_FIELDS = ("match_grade",)


def scrub(reason: str) -> str:
    r = re.sub(r"https?://\S+", "<url>", reason or "")
    r = re.sub(r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b", "<id>", r)
    r = re.sub(r"\b[A-Za-z0-9_-]{20,}\b", "<id>", r)
    r = re.sub(r"\bat \d{4}-\d{2}-\d{2}T[\d:.]+Z", "at <time>", r)
    return r


def dataset_stats(name: str, rows: List[Dict[str, Any]], summary: Dict[str, Any]) -> Dict[str, Any]:
    missing = [r for r in rows if not r.get("source_record_id") and not (r.get("null_reasons") or {})]
    gaps = [r for r in rows if not r.get("source_record_id") and (r.get("null_reasons") or {})]
    content = Counter(hashlib.sha256(json.dumps({k: v for k, v in r.items() if k not in RUN_FIELDS},
                                                sort_keys=True, default=str).encode()).hexdigest() for r in rows)
    dupes = sum(n - 1 for n in content.values() if n > 1)
    grades = Counter(str(r.get(f)) for r in rows for f in GRADE_FIELDS if f in r)
    nulls = Counter()
    for r in rows:
        for field, reason in (r.get("null_reasons") or {}).items():
            nulls[(field, scrub(str(reason)))] += 1
    return {"dataset": name, "status": summary.get("status", "not built"), "rows": len(rows),
            "missing_source_record": len(missing), "gap_rows": len(gaps), "duplicate_rows": dupes,
            "grades": dict(grades), "nulls": nulls, "reason": summary.get("reason")}


def write_report(ctx, datasets: List[str]) -> Path:
    stats = []
    for name in dict.fromkeys(datasets):
        out = ctx.out_dir(name)
        s = json.loads((out / "run_summary.json").read_text()) if (out / "run_summary.json").exists() else {}
        stats.append(dataset_stats(name, ctx.rows(name) or ctx.rows_partial(name) or [], s))
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORT_DIR / ("%s.md" % ctx.run_id)
    bad = [s for s in stats if s["missing_source_record"]]
    lines = ["# Dataset quality report: `%s`" % ctx.run_id, "",
             "Generated by `python -m apps.api.jobs.datasets quality --run-id %s`. Counts only; no vendor data." % ctx.run_id, "",
             "- Replay mode: **%s**. Seed source: **%s**. Config version: `%s`." % (ctx.replay, ctx.seed_source, ctx.config.get("config_version")),
             "- Rows missing a source record (must be zero): **%s**." % ("0 ✔" if not bad else "%d ✘ in %s" % (
                 sum(s["missing_source_record"] for s in bad), ", ".join(s["dataset"] for s in bad))),
             "- *Gap rows* have no source record because the call could not be made or returned nothing to store; each carries its reason.", "",
             "## Summary", "",
             "| Dataset | Status | Rows | Missing source record | Gap rows | Duplicate rows | Match grades |",
             "|---|---|---|---|---|---|---|"]
    for s in stats:
        g = ", ".join("%s: %d" % (k, v) for k, v in sorted(s["grades"].items())) or "-"
        lines.append("| `%s` | %s | %d | %d | %d | %d | %s |" % (s["dataset"], s["status"], s["rows"],
                     s["missing_source_record"], s["gap_rows"], s["duplicate_rows"], g))
    blocked = [s for s in stats if s["status"] == "blocked"]
    if blocked:
        lines += ["", "## Blocked datasets", ""] + ["- `%s`: %s" % (s["dataset"], scrub(s["reason"] or "")) for s in blocked]
    lines += ["", "## Null values and why", ""]
    for s in stats:
        if not s["nulls"]:
            continue
        lines += ["### `%s`" % s["dataset"], "", "| Field | Reason | Rows |", "|---|---|---|"]
        for (field, reason), n in s["nulls"].most_common():
            lines.append("| `%s` | %s | %d |" % (field, reason.replace("|", "/"), n))
        lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
