'use client'

import { ExternalLink, ListPlus, Presentation } from 'lucide-react'
import { useCase } from '@/components/shell/CaseContext'
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { DemoBadge } from '@/components/common/DemoBadge'
import { CertaintyMark } from '@/components/ui-kit/CertaintyMark'
import { MoneyAmount } from '@/components/ui-kit/MoneyAmount'
import { TypologyBadge } from '@/components/ui-kit/TypologyBadge'
import { pathsOfConcern, type PathOfConcern } from '@/lib/money'
import { pathStory } from '@/lib/narrative'
import { useWorkspace } from '@/lib/store'
import { TYPOLOGIES, typologyFit } from '@/lib/typologies'
import type { CaseFile } from '@/lib/types'

/** Step-through narrative for one path (regulator prompt 25), generated by lib/narrative.ts. */
export function PathStorySheet() {
  const c = useCase()
  const { storyPathId, setStoryPathId } = useWorkspace()
  const path = storyPathId ? pathsOfConcern(c, 50).find((p) => p.id === storyPathId) : undefined
  return (
    <Sheet open={!!path} onOpenChange={(o) => !o && setStoryPathId(null)} modal={false}>
      <SheetContent side="right" className="w-full gap-0 overflow-y-auto p-0 sm:max-w-lg" onInteractOutside={(e) => e.preventDefault()}>
        {path && <PathStoryBody c={c} path={path} />}
      </SheetContent>
    </Sheet>
  )
}

export function PathStoryBody({ c, path, large = false }: { c: CaseFile; path: PathOfConcern; large?: boolean }) {
  const story = pathStory(c, path)
  const { packet, togglePacketItem, setPresenting, setSelectedEntityId } = useWorkspace()
  const inPacket = packet.some((p) => p.kind === 'path' && p.id === path.id && p.caseId === c.id)
  const byId = new Map(c.entities.map((e) => [e.id, e]))
  return (
    <>
      <SheetHeader className="gap-2 border-b border-border p-5 pr-12">
        <div className="flex flex-wrap items-center gap-2">{c.kind === 'demo' && <DemoBadge />}</div>
        <SheetTitle className={large ? 'text-2xl' : 'text-lg'}>Path story</SheetTitle>
        <SheetDescription>{story.endpoint}</SheetDescription>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            aria-pressed={inPacket}
            onClick={() => togglePacketItem({ kind: 'path', id: path.id, caseId: c.id, label: story.endpoint })}
            className="flex items-center gap-1 rounded-md border border-ink px-2 py-1 text-xs font-semibold hover:bg-ink hover:text-paper focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            <ListPlus className="size-3.5" aria-hidden="true" />
            {inPacket ? 'In referral packet' : 'Add to referral packet'}
          </button>
          <button type="button" onClick={() => setPresenting(true)} className="flex items-center gap-1 rounded-md border border-border px-2 py-1 text-xs font-medium hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
            <Presentation className="size-3.5" aria-hidden="true" />
            Present
          </button>
        </div>
      </SheetHeader>
      <ol className="flex flex-col gap-3 p-5">
        {story.steps.map((s) => {
          const e = s.entityId ? byId.get(s.entityId) : undefined
          const fits = e ? TYPOLOGIES.filter((t) => typologyFit(e, c, t).matched.length > 0) : []
          return (
            <li key={s.n} className="flex flex-col gap-2 rounded-md border border-border p-3">
              <span className="text-xs font-semibold text-muted-foreground">Step {s.n}</span>
              <p className={large ? 'text-lg' : 'text-sm'}>{s.text}</p>
              <div className="flex flex-wrap items-center gap-2">
                {s.amount !== null && <MoneyAmount value={s.amount} certainty={s.certainty} />}
                {s.amount === null && <CertaintyMark certainty={s.certainty} />}
              </div>
              {s.indicators.length > 0 && (
                <ul className="flex flex-wrap gap-1">
                  {s.indicators.map((i) => (
                    <li key={i} className="rounded-full bg-muted px-2 py-0.5 text-[11px]">{i}</li>
                  ))}
                </ul>
              )}
              {fits.length > 0 && (
                <div className="flex flex-wrap gap-1">
                  {fits.map((t) => (
                    <TypologyBadge key={t.id} typology={t} short />
                  ))}
                </div>
              )}
              <div className="flex flex-wrap gap-3 text-xs">
                {e && (
                  <button type="button" onClick={() => setSelectedEntityId(e.id)} className="font-semibold text-foreground underline underline-offset-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
                    View record: {e.name}
                  </button>
                )}
                {s.sourceUrl && (
                  <a href={s.sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 underline underline-offset-2">
                    <ExternalLink className="size-3" aria-hidden="true" />
                    Source record
                  </a>
                )}
              </div>
            </li>
          )
        })}
        <li className="flex flex-col gap-2 rounded-md border-2 border-ink p-3">
          <span className="text-xs font-semibold text-muted-foreground">Endpoint</span>
          <p className={large ? 'text-lg font-semibold' : 'text-sm font-semibold'}>{story.endpoint}</p>
          <p className="text-xs font-semibold">What is not known</p>
          <ul className="list-disc pl-5 text-sm">
            {story.notKnown.map((n) => (
              <li key={n}>{n}</li>
            ))}
          </ul>
        </li>
      </ol>
    </>
  )
}
